### ISSUE TITLE
Generating a count/abundance matrix from LoRTIA outputs

### ISSUE THREAD

**Issue by shaniAmare** [zsolt-balazs/LoRTIA#2]
Hi @zsolt-balazs ,

I am wondering what outputs mentioned in the wiki and (if needed) any other downstream processing should be used if I want to get an isoform/gene count matrix with the category of the identified transcripts/genes (e.g. full-length, novel, full-length known, etc.).

Many thanks!
Shani.

**Comment by zsolt-balazs** [comment]
Hi Shani!

The outputs {prefix}_tr.tsv and {prefix}_tr.gff3 both contain the information of transcript counts. However, I would warn against using such outputs for measuring gene expression, because these transcript counts only include counts of reads that exactly depict the transcripts. And how many reads a given transcript is represented by often depends more on the library prep, chemistry and wet lab factors in general than actual gene expression. These outputs are suitable for transcript discovery, annotation or comparing libraries in their ability to get full-length transcripts, but no so much to do differential gene expression. If you want to do differential gene expression using long-read data, you can use bedtools to get a count matrix on the _tr.gff3 annotation, I think that would be more informative about the true gene expression.

Best wishes,

Zsolt
